cursor #e5e2e2
cursor_text_color #c6c6cc

foreground            #e5e2e2
background            #131314
selection_foreground  #2f3035
selection_background  #c6c6cc
url_color             #c3c6d4

color0   #131314
color1   #f36d90
color2   #6ad47b
color3   #fff972
color4   #b6b9c9
color5   #535662
color6   #c3c6d4
color7   #d1d3de
color8   #7f8189
color9   #ff9fb8
color10  #a5feb3
color11  #fffba5
color12  #d9dce9
color13  #f0f3ff
color14  #f5f7ff
color15  #f8f9ff
