# Personal Aliases
alias ntop="sudo nethogs"
alias ttp="tt -n 100 -blockcursor -json >> ~/.cache/tt.out"
alias c="wl-copy"
alias cl="fc -ln -1 | wl-copy" 
alias hot="sudo create_ap wlp2s0 wlp2s0 EDITH jarvis726"
alias pn="pnpm"
alias nv="nvim"
alias subs="subliminal download -l en *.mp4"
alias ff="fastfetch"
alias ssh="kitty +kitten ssh"
alias dy="dysk"
alias bt="btop"
alias zl="zellij"
alias zj="zellij -l simple"
alias zjd="zellij"
alias zjn="zellij -l simple attach --create"
alias oc="opencode"
alias open="xdg-open"
alias lzs="lazysql"
alias vis="vi-sql"
alias lzd="lazydocker"
alias tm="tmux"

# To clean aliases
alias svn="svn --config-dir \"$XDG_CONFIG_HOME\"/subversion"

if type eza &>/dev/null; then
  alias l="eza --icons=always"
  alias la="eza -a --icons=always"
  alias lh="eza -ad --icons=always .*"
  alias ll="eza -lg --icons=always"
  alias lla="eza -lag --icons=always"
  alias llh="eza -lagd --icons=always .*"
  alias ls="eza --icons=always"
  alias lt2="eza -lTg --level=2 --icons=always"
  alias lt3="eza -lTg --level=3 --icons=always"
  alias lt4="eza -lTg --level=4 --icons=always"
  alias lt="eza -lTg --icons=always"
  alias lta2="eza -lTag --level=2 --icons=always"
  alias lta3="eza -lTag --level=3 --icons=always"
  alias lta4="eza -lTag --level=4 --icons=always"
  alias lta="eza -lTag --icons=always"
fi
