cursor #e5e1e4
cursor_text_color #c7c5ce

foreground            #e5e1e4
background            #131315
selection_foreground  #2e303b
selection_background  #c5c5d4
url_color             #c4c8e9

color0   #131315
color1   #ff7296
color2   #74e988
color3   #ffd872
color4   #b3b7dd
color5   #4c4f6b
color6   #c4c8e9
color7   #e5e7f4
color8   #8c8d97
color9   #ff9fb7
color10  #a5ffb5
color11  #ffe6a5
color12  #dce0ff
color13  #e2e5ff
color14  #eceeff
color15  #f8f9ff
