# font_family  Jet Brains Mono SemiBold
font_family       Jet Brains Mono Nerd Font
font_size         14.0
bold_font         auto
italic_font       auto
bold_italic_font  auto

cursor_shape  block
cursor_trail  10
cursor_trail_start_threshold  0
cursor_trail_decary  0.01 0.05
cursor_blink  true

background_opacity       0.8
confirm_os_window_close  0
scrollback_lines         2000
wheel_scroll_min_lines   1
enable_audio_bell        no
# selection_foreground     none
# selection_background     none
window_padding_width     4
# foreground         #dddddd
# background         #000000
# cursor             #dddddd
shell_integration  no-cursor

# Tab configuration
tab_bar_align          center
tab_bar_margin_width   9
tab_bar_margin_height  1 0
tab_bar_style          separator
tab_bar_min_tabs       2
tab_separator          ""

# tab_bar_background       #36a3d9
# inactive_tab_background  #36a3d9
# inactive_tab_foreground  #0e1419
# active_tab_background    #0e1419
# active_tab_foreground    #E7C547

# Mouse and key mappings 
map ctrl+1           goto_tab 1
map ctrl+2           goto_tab 2
map ctrl+3           goto_tab 3
map ctrl+4           goto_tab 4
map ctrl+5           goto_tab 5
map ctrl+6           goto_tab 6
map ctrl+7           goto_tab 7
map ctrl+8           goto_tab 8
map ctrl+9           goto_tab 9
map ctrl+10          goto_tab 1
map ctrl+shift+f     launch --type=overlay --stdin-source=@screen_scrollback /usr/bin/fzf --no-sort --no-mouse --exact -i
map ctrl+alt+t		 new_tab_with_cwd
mouse_map left       click ungrabbed mouse_handle_click prompt
mouse_map ctrl+left  click ungrabbed mouse_handle_click link

# Make kitty send different keys when ctrl + KEY is pressed
map ctrl+shift+j send_key ctrl+alt+j
map ctrl+shift+k send_key ctrl+alt+k

include ./theme.conf


# BEGIN_KITTY_THEME
# Tokyo Night Moon
include current-theme.conf
# END_KITTY_THEME
